name: APOSNF-LOIS-QS
'on':
  workflow_dispatch: null
  push:
    branches:
      - main
permissions:
  contents: write
env:
 env: 'dev'
jobs:
 SmokeTest:
    runs-on: ubuntu-latest
    steps:
      - name: Call environment-specific workflow
        run: |
          if [ $env == 'dev' ]; then
          steps:
      - uses: actions/checkout@v3
        call-workflow1:
          uses: ./.github/workflows/workflow1.yaml
            elif [ $env == 'test' ]; then
           run:|
            echo "DemoHelp"
            else
            echo "Unknown environment"
            exit 1
