name: My Workflow
on:
  push:
    branches:
      - master
 
jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      LOIS_CLIENT_ID_QS: ${{ secrets.LOIS_CLIENT_ID_QS }}
    steps:
      - name: Use a secret
        env:
          SECRET_VALUE: ${{ secrets.LOIS_CLIENT_ID_QS }}
        run: echo '${{SECRET_VALUE}}'
