name: APOSNF-LOIS-QS
'on':
  workflow_dispatch: null
  push:
    branches:
      - master
permissions:
  contents: write
env:
 env: 'test'
jobs:
 SmokeTest:
    runs-on: ubuntu-latest
    steps:
      - name: Call environment-specific workflow
        run: |
          if [ $env == 'dev' ]; then
           jobs:
            call-workflow-in-localrepo:
             uses : ./.github/workflows/reusableworkflow.yml
          elif [ $env == 'test' ]; then
           jobs:
            call-workflow-in-localrepo:
             uses : ./.github/workflows/QS.yml
          else
            echo "Unknown environment"
            exit 1
          fi
