name: APOSNF-LOIS-QS
 
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to run: dev or test'
        required: true
        default: 'dev'
 
permissions:
  contents: write
 
jobs:
  SmokeTest:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger environment-specific workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
            repository:{repo}
          workflow: reusableworkflow.yml  # Change this to your actual workflow file name
          ref: master
          inputs: |
            env: ${{ github.event.inputs.env }}
