name: Environment Specific Workflow
 
on:
  push:
    branches:
      - master
jobs:
  publish:
    environment: QSEnv    # <--- /!\ Here is the link to the environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Some more steps here ...
    - name: Publish to Test PyPI
      env:
        LOIS_CLIENT_ID_QS: ${{ secrets.LOIS_CLIENT_ID_QS }}
        LOIS_CLIENT_SECRET_QS: ${{ secrets.LOIS_CLIENT_SECRET_QS }}
        LOIS_PASSPHRASE_QS: ${{ secrets.LOIS_PASSPHRASE_QS }}
      run: |
        echo KEY: '${{secrets.LOIS_CLIENT_ID_QS}}'
