on:
  workflow_call:
    secrets:
      QS_Credentials:
        description: >
          QS credentials which will be used for test execution on QS ENV.
        required: true
      TEST_Credentials:
        description: >
          TEST credentials which will be used for test execution on TEST ENV.
        required: true
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Select the environment'
        required: true
        options:
          - TEST
          - QS
