name: APOSNF-LOIS-QS
 
on:
  workflow_dispatch:
  push:
    branches:
      - master
 
permissions:
  contents: write
 
env:
  ENVIRONMENT: 'test'
 
jobs:
  SmokeTest:
    runs-on: ubuntu-latest
    if: ${{ ENVIRONMENT == 'test' }}
    steps:
      - name: Call environment-specific workflow
        uses: ./.github/workflows/reusableworkflow.yml 
        
         
