name: Environment Specific Workflow
 
on:
  push:
    branches:
      - master
 
jobs:
  publish:
    environment: Test    # <--- /!\ Here is the link to the environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up environment
        run: |
          #if [ "${{ environment }}" == "Test" ]; then
            echo "Setting up QS environment..."
          - name: Publish to Test PyPI
            env:
            LOISTESTENVCLIENTID: ${{ secrets.LOISTESTENVCLIENTID }}
           LOISTESTENVCLIENTSECRET: ${{ secrets.LOISTESTENVCLIENTSECRET }}
          LOISTESTENVPASSPHRASE: ${{ secrets.LOISTESTENVPASSPHRASE }}
          echo "Setting up QS environment..."
          echo "Setting up QS environment..."
          echo "Setting up QS environment..."
            # Commands to set up development environment
      
 

