name: Environment Specific Workflow
 
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        environment: [QSEnv, TestEnv]
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
 
      - name: Install dependencies
        run: npm install
 
      - name: Set up environment
        run: |
          if [ "${{ matrix.environment }}" == "QSEnv" ]; then
            echo "Setting up development environment..."
            # Commands to set up development environment
          elif [ "${{ matrix.environment }}" == "TestEnv" ]; then
            echo "Setting up production environment..."
            # Commands to set up production environment
          else
            echo "Unknown environment"
            exit 1
          fi
 
      - name: Run Cypress tests
        run: |
          if [ "${{ matrix.environment }}" == "QSEnv" ]; then
            echo "Running development tests..."
            npx cypress run --config baseUrl=http://localhost:8000
          elif [ "${{ matrix.environment }}" == "TestEnv" ]; then
            echo "Running production tests..."
          else
            echo "Unknown environment"
            exit 1
          fi
