name: APOSNF-LOIS-QS
'on':
  workflow_dispatch: null
  push:
    branches:
      - main
permissions:
  contents: write
env:
 env: 'dev'
jobs:
 SmokeTest:
    runs-on: ubuntu-latest
    steps:
      - name: Call environment-specific workflow
        run: |
          if [ $env == 'dev' ]; then
    env:
    LOISTESTENVCLIENTID: ${{ secrets.LOISTESTENVCLIENTID }}
    LOISTESTENVCLIENTSECRET: ${{ secrets.LOISTESTENVCLIENTSECRET }}
    LOISTESTENVPASSPHRASE: ${{ secrets.LOISTESTENVPASSPHRASE }}
 
    jobs:
      cypress-run:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Setup Node.js environment
            uses: actions/setup-node@v4.0.0
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
          - name: Cypress run
            uses: cypress-io/github-action@v6
            with:
            spec: cypress/e2e/LOIS-Test-Arteon/01_SmokeTest
          - name: Final Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Output Report
          path: /home/runner/work/aposnf-qa/aposnf-qa/cypress/reports
          retention-days: 1
            elif [ $env == 'test' ]; then
           run:|
            echo "DemoHelp"
            else
            echo "Unknown environment"
            exit 1
          fi
