name: Environment Specific Workflow
 
on:
  push:
    branches:
      - master
 
jobs:
  publish:
    environment: Test    # <--- /!\ Here is the link to the environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up environment
        run: |
            echo "Setting up QS environment..."
      - name: Publish to Test PyPI
        env:
               LOIS_CLIENT_ID_QS: ${{ secrets.LOIS_CLIENT_ID_QS }}
               LOIS_CLIENT_SECRET_QS: ${{ secrets.LOIS_CLIENT_SECRET_QS }}
               LOIS_PASSPHRASE_QS: ${{ secrets.LOIS_PASSPHRASE_QS }};
                 echo LOIS_CLIENT_ID_QS
                 echo LOIS_CLIENT_ID_QS
               # Commands to set up development environment
      
 

