name: Choice Parameter Workflow
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'dev'
        options:
          - dev
          - staging
          - production
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
 
      - name: Deploy to selected environment
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }} environment"
          GITHUB_WORKSPACE/trigger_workflow.sh
